# Site settings
title: caian's website
description: >
  idunno
repository: https://github.com/caianrais/site
baseurl: /
url: https://caian.org

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: caian r. ertl
email: caianrais@pm.me

navigation:
  - text: Home
    url: /

social:
  - service: github
    username: caianrais
    link: https://github.com/caianrais
