# Site settings

title: caian.org
email: hi@caian.org
description: >
  Personal page, blog, portfolio etc
baseurl: ''
url: https://caian.org

incremental: true
source: content
destination: site

# Build settings
markdown: kramdown

sass:
  style: nested
  sourcemap: never
