# Site settings
title: Caian R. Ertl
email: hi@caian.org
description: >
  Personal page, blog, portfolio etc
baseurl: ""
url: https://caian.org

# SEO settings
author: Caian Rais Ertl
social:
  name: Caian Rais Ertl
  links:
    - https://github.com/caiertl

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - venv
  - vendor
sass:
  style: compressed

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
