baseURL      = 'https://caian.org'
languageCode = 'en-us'
title        = 'caian.org'
theme        = 'pereskia'
copyright    = 'kopimi'

[[menu.main]]

    name   = 'Home'
    url    = '/'
    weight = 1

[[menu.main]]

    name   = 'Posts'
    url    = '/posts'
    weight = 2

[[menu.main]]

    name   = 'Contact'
    url    = '/contact'
    weight = 3

[[menu.main]]

    name   = 'About'
    url    = '/about'
    weight = 4


[params]

    rss = false

    description = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla a urna placerat, sollicitudin sapien eu, pellentesque metus. Nulla vel libero tincidunt sapien mollis lobortis sit amet sit amet libero. Suspendisse ut tellus sit amet elit placerat venenatis ut sit amet tellus. Nulla orci mauris, cursus in turpis sed, dictum lobortis ipsum. Vivamus eleifend imperdiet mauris et efficitur. Aenean et mauris at purus tincidunt interdum. Quisque consectetur facilisis leo, ac luctus nisl tempor at. sum sit dolor amet'

    showReadTime = true

    logo = 'images/nike-2.svg'

    [params.comments]

        enabled = false
