# Site settings

title: caian.org
email: hi@caian.org
description: >
  Personal page, blog, portfolio etc
baseurl: ''
url: https://caian.org

incremental: true
source: content
destination: public

# Build settings
plugins:
  - jekyll-pug
  - jekyll-minifier
  - jekyll-target-blank

markdown: kramdown

sass:
  style: compressed
  sourcemap: never

jekyll-pug:
  minify: true
