title: caian.org
email: hi@caian.org
url: https://caian.org
baseurl: ''
description: >
  Personal page, blog, portfolio etc

incremental: true
source: content
destination: public

plugins:
  - jekyll-pug
  - jekyll-minifier
  - jekyll-target-blank

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

sass:
  sass_dir: assets/css
  style: compressed
  sourcemap: never
