baseURL      = 'https://caian.org'
languageCode = 'en-us'
title        = 'caian.org'
theme        = 'cactus'
copyright    = 'kopimi'

[[menu.main]]

    name   = 'Home'
    url    = '/'
    weight = 1

[[menu.main]]

    name   = 'Writings'
    url    = '/posts'
    weight = 2

[[menu.main]]

    name   = 'Tags'
    url    = '/tags'
    weight = 3

[[menu.main]]

    name   = 'About'
    url    = '/about'
    weight = 4


[params]

    rss = true

    description = 'lorem ipsum sit dolor amet'
    showReadTime = true

    [params.comments]

        enabled = false
