title: caian.org
email: hi@caian.org
url: https://caian.org
description: Personal page, blog, portfolio etc
rss: /blog/feed.xml

source: dist/intermediate
destination: dist/public

plugins:
  - jekyll-minifier
  - jekyll-target-blank
  - jekyll-loading-lazy
  - jekyll-seo-tag
  - liquid_reading_time
  - liquid_pluralize

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

sass:
  sass_dir: assets/css
  style: compressed
  sourcemap: never
